apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    "cli.sigs.k8s.io/cli.v1alpha1.ResourceCommandList": ""
    "cli.sigs.k8s.io/cli.v1alpha1.ServiceCommandList": ""
  annotations:
    "cli.sigs.k8s.io/cli.v1alpha1.ResourceCommandList": '{"items":[{"command":{"path":["create"],"use":"deployment","aliases":["deploy","deployments"],"short":"Create a deployment with the specified name.","long":"Create a deployment with the specified name.","example":"# Create a new deployment named my-dep that runs the busybox image.\nkubectl create deployment --name my-dep --image=busybox\n","flags":[{"name":"name","type":"String","stringValue":"","description":"deployment name"},{"name":"image","type":"String","stringValue":"","description":"Image name to run."},{"name":"replicas","type":"Int","intValue":1,"description":"Image name to run."},{"name":"namespace","type":"String","stringValue":"default","description":"deployment namespace"}]},"requests":[{"group":"apps","version":"v1","resource":"deployments","operation":"Create","bodyTemplate":"apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{index .Flags.Strings \"name\"}}\n  namespace: {{index .Flags.Strings \"namespace\"}}\n  labels:\n    app: nginx\nspec:\n  replicas: {{index .Flags.Ints \"replicas\"}}\n  selector:\n    matchLabels:\n      app: {{index .Flags.Strings \"name\"}}\n  template:\n    metadata:\n      labels:\n        app: {{index .Flags.Strings \"name\"}}\n    spec:\n      containers:\n      - name: {{index .Flags.Strings \"name\"}}\n        image: {{index .Flags.Strings \"image\"}}\n","saveResponseValues":[{"name":"responsename","jsonPath":"{.metadata.name}"}]}],"output":"deployment.apps/{{index .Responses.Strings \"responsename\"}} created\n"}]}'
    "cli.sigs.k8s.io/cli.v1alpha1.ServiceCommandList": '{"items":[{"command":{"use":"get-random","short":"Get a random resource.","long":"Get a random resource.","example":"kubectl get-random\n","flags":[{"name":"kind","type":"String","stringValue":"Pod","description":"kind of resource to get"}]},"requests":[{"serviceName":"nginx","serviceNamespace":"default","protocol":"http","operation":"Get","saveResponseValues":[{"name":"responsename","jsonPath":"{.hello}"}]}],"output":"{{index .Responses.Strings \"responsename\"}}\n"},{"command":{"use":"post-random","short":"Get a random resource.","long":"Get a random resource.","example":"kubectl post-random\n","flags":[{"name":"name","type":"String","stringValue":"","description":"deployment name"},{"name":"image","type":"String","stringValue":"","description":"Image name to run."},{"name":"replicas","type":"Int","intValue":1,"description":"Image name to run."},{"name":"namespace","type":"String","stringValue":"default","description":"deployment namespace"}]},"requests":[{"serviceName":"nginx","serviceNamespace":"default","protocol":"http","operation":"Post","urlTemplate":"{{index .Flags.Strings \"namespace\"}}/{{index .Flags.Strings \"name\"}}","paramsTemplates":{"name":"{{index .Flags.Strings \"name\"}}","namespace":"{{index .Flags.Strings \"namespace\"}}"},"bodyTemplate":"apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{index .Flags.Strings \"name\"}}\n  namespace: {{index .Flags.Strings \"namespace\"}}\n  labels:\n    app: nginx\nspec:\n  replicas: {{index .Flags.Ints \"replicas\"}}\n  selector:\n    matchLabels:\n      app: {{index .Flags.Strings \"name\"}}\n  template:\n    metadata:\n      labels:\n        app: {{index .Flags.Strings \"name\"}}\n    spec:\n      containers:\n      - name: {{index .Flags.Strings \"name\"}}\n        image: {{index .Flags.Strings \"image\"}}\n","saveResponseValues":[{"name":"responsename","jsonPath":"{.hello}"}]}],"output":"{{index .Responses.Strings \"responsename\"}}\n"}]}'
  name: clitestresources.test.cli.sigs.k8s.io
spec:
  group: test.cli.sigs.k8s.io
  names:
    kind: CLITestResource
    plural: clitestresources
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            replicas:
              format: int32
              type: integer
            image:
              type: string
          type: object
        status:
          type: object
  version: v1alpha1
