steps:
- name: 'ubuntu'
  args: ['pwd']
- name: 'ubuntu'
  args: ['ls']
- name: 'ubuntu'
  args: ['ls', 'cmd', 'kube', 'internal']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'kube', 'cmd/kube/internal/main.go']
  env: ['PROJECT_ROOT=k8s.io/kubectl']
